// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFJ0B4DTINVW2dXmf7R7KPVQXTanuXgQQ',
    appId: '1:394828717914:web:f5e65d462945a088d25d63',
    messagingSenderId: '394828717914',
    projectId: 'mo3alim-cc44a',
    authDomain: 'mo3alim-cc44a.firebaseapp.com',
    storageBucket: 'mo3alim-cc44a.appspot.com',
    measurementId: 'G-2SQQ5Q1K4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR5OB0DyIodXXHtpCd7ZkWUie0Vmk115k',
    appId: '1:394828717914:android:5dbfc5c87a24d6a0d25d63',
    messagingSenderId: '394828717914',
    projectId: 'mo3alim-cc44a',
    storageBucket: 'mo3alim-cc44a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPVN0kd1bb_xUPN6eGNNDNJNYuFouqK0E',
    appId: '1:394828717914:ios:dd051759df66ba17d25d63',
    messagingSenderId: '394828717914',
    projectId: 'mo3alim-cc44a',
    storageBucket: 'mo3alim-cc44a.appspot.com',
    iosClientId: '394828717914-0d8f8rcemda89skmfjo43np735hd4v55.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
